/**
 * Cozy Café — Menu product data
 * Prices preserved exactly as supplied. Ingredients are presentation-only.
 */

window.COZY_MENU = {
  breakfast: [
    {
      id: "butter-croissant",
      name: "Butter Croissant",
      price: "$200",
      description: "Buttery · Flaky · Warm",
      ingredients: ["Flour", "Butter", "Milk", "Sugar", "Salt"],
      image: "assets/images/butter-croissant.jpg",
      alt: "Golden flaky butter croissant on a cream ceramic plate",
      size: "featured",
    },
    {
      id: "pancake-stack",
      name: "Pancake Stack",
      price: "$800",
      description: "Fluffy · Sweet · Golden",
      ingredients: ["Flour", "Milk", "Eggs", "Butter", "Maple Syrup"],
      image: "assets/images/pancake-stack.jpg",
      alt: "Fluffy pancake stack with warm syrup and butter",
      size: "medium",
    },
    {
      id: "chocolate-croissant",
      name: "Chocolate Croissant",
      price: "$500",
      description: "Flaky · Rich · Chocolatey",
      ingredients: ["Flour", "Butter", "Chocolate", "Milk", "Sugar"],
      image: "assets/images/chocolate-croissant.jpg",
      alt: "Flaky chocolate croissant with visible chocolate center",
      size: "medium",
    },
    {
      id: "cinnamon-roll",
      name: "Cinnamon Roll",
      price: "$300",
      description: "Spiced · Soft · Glazed",
      ingredients: ["Flour", "Cinnamon", "Butter", "Sugar", "Milk"],
      image: "assets/images/cinnamon-roll.jpg",
      alt: "Warm cinnamon roll with light glaze",
      size: "small",
    },
    {
      id: "banana-bread",
      name: "Banana Bread Slice",
      price: "$1,000",
      description: "Moist · Sweet · Comforting",
      ingredients: ["Banana", "Flour", "Butter", "Sugar", "Eggs"],
      image: "assets/images/banana-bread.jpg",
      alt: "Thick slice of golden banana bread",
      size: "small",
    },
    {
      id: "blueberry-muffin",
      name: "Blueberry Muffin",
      price: "$1,200",
      description: "Berry · Tender · Fresh",
      ingredients: ["Blueberries", "Flour", "Milk", "Sugar", "Butter"],
      image: "assets/images/blueberry-muffin.jpg",
      alt: "Freshly baked blueberry muffin",
      size: "small",
    },
    {
      id: "cheese-danish",
      name: "Cheese Danish",
      price: "$1,400",
      description: "Creamy · Golden · Flaky",
      ingredients: ["Flour", "Butter", "Cream Cheese", "Sugar", "Milk"],
      image: "assets/images/cheese-danish.jpg",
      alt: "Flaky cheese Danish with creamy center",
      size: "small",
    },
    {
      id: "toast-jam",
      name: "Toast & Jam",
      price: "$900",
      description: "Simple · Bright · Classic",
      ingredients: ["Bread", "Butter", "Fruit Jam"],
      image: "assets/images/toast-jam.jpg",
      alt: "Rustic toast with fruit jam on a cream plate",
      size: "small",
    },
  ],

  lunch: [
    {
      id: "club-sandwich",
      name: "Club Sandwich",
      price: "$500",
      description: "Stacked · Fresh · Satisfying",
      ingredients: ["Bread", "Chicken", "Lettuce", "Tomato", "Mayo"],
      image: "assets/images/club-sandwich.jpg",
      alt: "Layered club sandwich with toasted bread and fresh fillings",
      size: "featured",
    },
    {
      id: "beef-burger",
      name: "Beef Burger",
      price: "$500",
      description: "Classic · Hearty · Bold",
      ingredients: ["Bun", "Beef", "Lettuce", "Tomato", "Sauce"],
      image: "assets/images/beef-burger.jpg",
      alt: "Classic café beef burger with fresh toppings",
      size: "medium",
    },
    {
      id: "chicken-burger",
      name: "Chicken Burger",
      price: "$800",
      description: "Crispy · Savory · Full",
      ingredients: ["Bun", "Chicken", "Lettuce", "Tomato", "Sauce"],
      image: "assets/images/chicken-burger.jpg",
      alt: "Crispy chicken burger with toasted bun",
      size: "medium",
    },
    {
      id: "chicken-sandwich",
      name: "Chicken Sandwich",
      price: "$200",
      description: "Simple · Warm · Easy",
      ingredients: ["Bread", "Chicken", "Lettuce", "Tomato"],
      image: "assets/images/chicken-sandwich.jpg",
      alt: "Freshly prepared chicken sandwich",
      size: "small",
    },
    {
      id: "veggie-sandwich",
      name: "Veggie Sandwich",
      price: "$100",
      description: "Fresh · Light · Bright",
      ingredients: ["Bread", "Greens", "Tomato", "Vegetables"],
      image: "assets/images/veggie-sandwich.jpg",
      alt: "Colorful fresh vegetable sandwich",
      size: "small",
    },
    {
      id: "french-fries",
      name: "French Fries",
      price: "$500",
      description: "Crispy · Golden · Salty",
      ingredients: ["Potato", "Salt", "Oil"],
      image: "assets/images/french-fries.jpg",
      alt: "Golden French fries in a simple café dish",
      size: "small",
    },
    {
      id: "meat-pie",
      name: "Meat Pie",
      price: "$800",
      description: "Flaky · Savory · Warm",
      ingredients: ["Pastry", "Meat", "Seasoning"],
      image: "assets/images/meat-pie.jpg",
      alt: "Golden savory meat pie with flaky crust",
      size: "small",
    },
    {
      id: "sausage-roll",
      name: "Sausage Roll",
      price: "$700",
      description: "Golden · Flaky · Hearty",
      ingredients: ["Pastry", "Sausage", "Seasoning"],
      image: "assets/images/sausage-roll.jpg",
      alt: "Golden flaky sausage roll",
      size: "small",
    },
    {
      id: "spring-rolls",
      name: "Spring Rolls",
      price: "$200",
      description: "Crispy · Light · Shareable",
      ingredients: ["Wrapper", "Vegetables", "Oil"],
      image: "assets/images/spring-rolls.jpg",
      alt: "Crispy golden spring rolls on a cream plate",
      size: "small",
    },
  ],
};
